#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & nitrogen --restore & picom & polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20
bspc config split_ratio          0.52
bspc config focused_border_color "#DEE3EC"
bspc config normal_border_color "#544E74"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
